server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 是否注册到其他eureka server节点，单机模式下设为false
    register-with-eureka: false
    # 是否从其他eureka server节点获取服务信息，单机模式下设为false
    fetch-registry: false
  instance:
    # renew频率，向Eureka服务发送renew信息，默认30秒，生产环境不建议修改
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该实例，默认90秒，生产环境不建议修改
    lease-expiration-duration-in-seconds: 15
    # 默认服务发现中心为本地
    hostname: localhost
  server:
    # eureka自我保护模式  默认打开
    enable-self-preservation: true