server:
  port: 5001
#  context-path: /user
####oauth2过滤器#############
security:
  oauth2:
    resource:
      filter-order: 3
spring:
  application:
    name: user-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sone?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
##不使用eureka自动获取服务列表
#uaa-service:
#  ribbon:
#    listOfServers: http://localhost:5000
#    eureka:
#      enabled: false